---
default:
  projects_refresh_period: 12
  users:
    allow_register: false
    allow_destroy: true
    password_min_chars: 6
  web_hooks:
    git_hub: 'http://localhost:3000/api/v1/projects/git_hub_activity_web_hook'

development:
  users:
    allow_register: true
 
test:

staging:

production:
