---
default:
  protocol: "http://"
  host: "karma.amberbit.com"
  projects_refresh_period: 12
  items_per_page: 20
  webhook_check_time: 0.0006944444444444445
  users:
    allow_register: false
    allow_destroy: true
    password_min_chars: 6
  web_hooks:
    git_hub:

  google_api:
    client_id:
    secret:
    callback_url:

  github_api:
    client_id:
    secret:

development:
  protocol: "http://"
  host: "localhost:8080"
  users:
    allow_register: true

test:

staging:

production:
  webhook_check_time: 0.25
