---
default:
  projects_refresh_period: 12
  items_per_page: 20
  users:
    allow_register: false
    allow_destroy: true
    password_min_chars: 6
  web_hooks:
    git_hub: 

  google_api:
    client_id: 
    secret: 
    callback_url: 


development:
  users:
    allow_register: true

test:

staging:

production:
