development:
  adapter: postgresql
  encoding: unicode
  database: karma_tracker_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: karma_tracker_test
  pool: 5
  username:
  password:

